export const ADD_USER_BEGIN = "ADD_USER_BEGIN";
export const ADD_USER_SUCCESS = "ADD_USER_SUCCESS";
export const ADD_USER_FAILURE = "ADD_USER_FAILURE";

export const USER_LOGIN_BEGIN = "USER_LOGIN_BEGIN";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAILURE = "USER_LOGIN_FAILURE";

export const ADD_WARDS_BEGINS = "ADD_WARDS_BEGINS";
export const ADD_WARDS_SUCCESS = "ADD_WARDS_SUCCESS";
export const ADD_WARDS_FAILURE = "ADD_WARDS_FAILURE";

export const FETCH_WARDS_BEGINS = "FETCH_WARDS_BEGINS";
export const FETCH_WARDS_SUCCESS = "FETCH_WARDS_SUCCESS";
export const FETCH_WARDS_FAILURE = "FETCH_WARDS_FAILURE";

export const ADD_INSTITUTION_BEGINS = "ADD_INSTITUTION_BEGINS";
export const ADD_INSTITUTION_SUCCESS = "ADD_INSTITUTION_SUCCESS";
export const ADD_INSTITUTION_FAILURE = "ADD_INSTITUTION_FAILURE";

export const FETCH_INSTITUTION_BEGINS = "FETCH_INSTITUTION_BEGINS";
export const FETCH_INSTITUTION_SUCCESS = "FETCH_INSTITUTION_SUCCESS";
export const FETCH_INSTITUTION_FAILURE = "FETCH_INSTITUTION_FAILURE";

export const ADD_COURSE_BEGINS = "ADD_COURSE_BEGINS";
export const ADD_COURSE_SUCCESS = "ADD_COURSE_SUCCESS";
export const ADD_COURSE_FAILURE = "ADD_COURSE_FAILURE";

export const FETCH_COURSE_BEGINS = "FETCH_COURSE_BEGINS";
export const FETCH_COURSE_SUCCESS = "FETCH_COURSE_SUCCESS";
export const FETCH_COURSE_FAILURE = "FETCH_COURSE_FAILURE";
